### ISSUE TITLE
(2) Use and Organize SCSS in Rails

### ISSUE THREAD

**Issue by yagihashib** [yagihashib/tc359_rails_final#2]

**Comment by yagihashib** [comment]
@chrisvfritz Hey Chris, I've finished organizing the SCSS for the app. Can you check to see if it meets the requirements?

**Comment by chrisvfritz** [comment]
This doesn't quite meet requirements.

> The only file in the root of the stylesheets directory is application.scss

Your application file isn't an SCSS file and it looks like more than that file are in the root of your stylesheets directory (everything else shoot be organized into subfolders).

> All SCSS is in logically organized folders

Apart from the issue mentioned above, I don't think I agree with the logic of a `styles` directory within `stylesheets`. Won't everything be styles? I recommend checking out some of the resources on the skill page or search for `rails scss organization` for examples of how different people choose to organize SCSS (there are a lot of "right" ways).

> Each SCSS file contains no more than 50 lines (without a very good reason)

It looks like `nav` and `userlineup` both have more than 50 lines. This is generally an indication that it'd be good to split styles up further into more specific modules, but if you have a reason for keeping it all together, I'm open to hearing the very good reason if there is one.

> You have correctly implemented the autoprefixer-rails gem to automatically include browser prefixes, when necessary

I don't see the autoprefixer-rails gem used in this project.

**Comment by yagihashib** [comment]
Hey Chris, I'm a bit confused about how to go about structuring submodules. 
I split up the navbar and made a folder for application.scss to inherit from:

-application.scss
  -navbar(folder)
    -navbar.scss
    -signedin.scss
    -signedout.scss

My question is should I be making another folder for submodules signedin.scss and signedout.scss and import them in navbar.scss like so?

-application.scss
  -navbar(folder)
    -navbar.scss
    -navbarmodules(folder)
      -signedin.scss
      -signedout.scss

**Comment by chrisvfritz** [comment]
I'd say that's up to you. I've seen people follow both patterns and I see the logic of both.

**Comment by yagihashib** [comment]
@chrisvfritz Ok, I was just wondering if there was a standard. I have organized the stylesheets folder, added the autoprefixer gem and split up all the modules so each is less than 50 lines. Can you take a look to make sure everything looks ok?

**Comment by chrisvfritz** [comment]
The organization looks really good. There are just two things I would update:

- Since the `base/variables` file is imported before everything else in your `application` file, you actually don't need to make sure to import them again in your other files - those variables are already available.
- For some of the repeated values, like black for the navbar background, I would extract them to variables such as `$navbar-background` (or if you prefer, `$nav-bg` for brevity). If this variable is only relevant to the file it's in, you can place it at the top of the file. Otherwise, you can place it in a navigation section of your variables file. It makes it so much easier to have all your "configuration" in variables, in one place, so that when you need to change something, it becomes very trivial.

**Comment by yagihashib** [comment]
@chrisvfritz For some reason I'm getting an SASS undefined variable error if I don't import them in each file. I am currently searching for a fix but if you something comes to mind let me know.

**Comment by chrisvfritz** [comment]
Ahh, I see. Since you're using SCSS to handle imports, the problem will be fixed if you delete the comments where sprockets also tries to handle importing (but doesn't know how to carry over variables from one file to another). Specifically, you'll delete the following from your application.scss file:

``` scss
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or any plugin's vendor/assets/stylesheets directory can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the bottom of the
 * compiled file so the styles you add here take precedence over styles defined in any styles
 * defined in the other CSS/SCSS files in this directory. It is generally better to create a new
 * file per style scope.
 *
 *= require_tree .
 *= require_self
 */
```

**Comment by yagihashib** [comment]
@chrisvfritz Awesome thanks that worked!

**Comment by chrisvfritz** [comment]
:+1: Looks great!

**Comment by chrisvfritz** [comment]
And... that's a 4.0! :tada: :balloon: :shipit: :metal:

**Comment by yagihashib** [comment]
Awesome! I really enjoyed and learned a lot from this class. Thanks for helping me learn ruby and rails!
