### ISSUE TITLE
(2) Visualize a bar chart (or other simple chart) with d3.js

### ISSUE THREAD

**Issue by yagihashib** [yagihashib/tc359_rails_final#4]

**Comment by yagihashib** [comment]
@chrisvfritz I've added a simple d3.js visualization for my Nbaplayer model on the index but it doesn't seem to load 100% of the time, only after I've added a player or refreshed the index page. Any idea why this could be?

**Comment by chrisvfritz** [comment]
I do indeed. :smiley: By default, Rails 4 uses a gem called turbolinks which will preload some links in the background for visitors, so that the page load seems instantaneous when they click on a link. A downside is your JS doesn't run again when turbolinks does its magic, replacing the body and updating the browser history.

There are two workarounds:

- Make your JS run on [turbolink's `page:load` event](http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links)
- [Remove turbolinks](http://blog.steveklabnik.com/posts/2013-06-25-removing-turbolinks-from-rails-4) from your project

**Comment by yagihashib** [comment]
Thanks! I've added code to make the JS run on page:load. Also, I plan on adding more data and axes to the chart but does the visualization meet the requirements at this point?

**Comment by chrisvfritz** [comment]
:+1: Looks great!
